# docker-compose.yml
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["/app/.venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    develop:
      watch: 
        - path: ./api/main.py
          action: sync
          target: /app/main.py
        - path: ./api/pyproject.toml
          action: rebuild
  other_mcp_server:
    build:
      context: ./other_mcp_server
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    command: ["/app/.venv/bin/uvicorn", "main:http_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    develop:
      watch: 
        - path: ./other_mcp_server/main.py
          action: sync
          target: /app/main.py
        - path: ./other_mcp_server/pyproject.toml
          action: rebuild