[project]
name = "other-mcp-server"
version = "0.1.0"
description = "Other MCP server for testing and development"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.4.0",
    "uvicorn>=0.34.2",
]
